// ============================================================================
// DELIVERY
// ============================================================================
// PRODUCTION ROLE:
//   Represents one physical movement/leg generated by a fulfillment plan.
//
// DEPENDS ON:
//   Standard types and DeliveryType.
//
// USED BY:
//   DeliveryPlanner -> simulation state -> visualization/reporting.
//
// DELIVERY TYPES:
//   STORE_TO_CUSTOMER
//   STORE_TO_STORE
//   WAREHOUSE_TO_STORE
//   WAREHOUSE_TO_CUSTOMER
//
// SHOULD CONTAIN:
//   - Source node.
//   - Destination node.
//   - Delivery type.
//   - Route returned by graph algorithms.
//   - Travel time/cost.
//
// IMPORTANT:
//   One order may generate multiple Delivery objects.
//   This enables split fulfillment.
//
// DO NOT:
//   Decide which fulfillment strategy is best here.
//   This object records the result of a decision.
#pragma once

#include <vector>

namespace logistics {

enum class DeliveryType {
    STORE_TO_CUSTOMER,
    STORE_TO_STORE,
    WAREHOUSE_TO_STORE,
    WAREHOUSE_TO_CUSTOMER
};

struct Delivery {
    int sourceNode{};
    int destinationNode{};
    DeliveryType type{};
    std::vector<int> route;
    double travelTime{};
    double cost{};
};

} // namespace logistics
